// Mock data used when API is unavailable (development / demo mode)

export const MOCK_NEEDS = [
  {
    id: 1,
    need_type: 'Food & Nutrition',
    location: 'Sundarbans Delta, WB',
    urgency: 'high',
    people_affected: 1200,
    lat: 21.9497,
    lng: 88.9264,
    description: 'Flooding has cut off food supply routes to isolated villages.',
  },
  {
    id: 2,
    need_type: 'Medical Aid',
    location: 'Murshidabad District',
    urgency: 'high',
    people_affected: 340,
    lat: 24.1833,
    lng: 88.2667,
    description: 'Outbreak of water-borne illness requiring immediate medical response.',
  },
  {
    id: 3,
    need_type: 'Shelter',
    location: 'Cooch Behar',
    urgency: 'medium',
    people_affected: 780,
    lat: 26.3245,
    lng: 89.4463,
    description: 'Cyclone damage left hundreds without stable shelter.',
  },
  {
    id: 4,
    need_type: 'Clean Water',
    location: 'Malda Town',
    urgency: 'medium',
    people_affected: 560,
    lat: 25.0108,
    lng: 88.1418,
    description: 'Contaminated groundwater affecting entire ward.',
  },
  {
    id: 5,
    need_type: 'Education Support',
    location: 'Bankura',
    urgency: 'low',
    people_affected: 210,
    lat: 23.2324,
    lng: 87.0753,
    description: 'Children unable to attend school due to lack of supplies.',
  },
  {
    id: 6,
    need_type: 'Livelihood',
    location: 'Purulia District',
    urgency: 'low',
    people_affected: 430,
    lat: 23.3327,
    lng: 86.3636,
    description: 'Drought-affected farmers need seeds and tools for next season.',
  },
]

export const MOCK_ASSIGNMENTS = [
  {
    id: 'T-001',
    title: 'Food Distribution Drive',
    location: 'Sundarbans Delta, WB',
    urgency: 'high',
    date: '2025-04-20',
    duration: '6 hrs',
    skills_needed: ['Logistics', 'Driving'],
    volunteers_needed: 12,
    volunteers_assigned: 7,
    description: 'Organize and distribute emergency food packets to flood-affected villages.',
    status: 'open',
  },
  {
    id: 'T-002',
    title: 'Mobile Medical Camp',
    location: 'Murshidabad District',
    urgency: 'high',
    date: '2025-04-18',
    duration: '8 hrs',
    skills_needed: ['Medical', 'First Aid'],
    volunteers_needed: 8,
    volunteers_assigned: 3,
    description: 'Set up and run a mobile medical camp for water-borne illness cases.',
    status: 'open',
  },
  {
    id: 'T-003',
    title: 'Shelter Repair Team',
    location: 'Cooch Behar',
    urgency: 'medium',
    date: '2025-04-22',
    duration: '10 hrs',
    skills_needed: ['Construction', 'Carpentry'],
    volunteers_needed: 20,
    volunteers_assigned: 11,
    description: 'Assist in repairing roofs and walls damaged by the recent cyclone.',
    status: 'open',
  },
  {
    id: 'T-004',
    title: 'Water Purification Setup',
    location: 'Malda Town',
    urgency: 'medium',
    date: '2025-04-24',
    duration: '4 hrs',
    skills_needed: ['Engineering', 'Water Sanitation'],
    volunteers_needed: 6,
    volunteers_assigned: 2,
    description: 'Install portable water purification units across the affected ward.',
    status: 'open',
  },
  {
    id: 'T-005',
    title: 'Education Kit Delivery',
    location: 'Bankura',
    urgency: 'low',
    date: '2025-04-28',
    duration: '3 hrs',
    skills_needed: ['Teaching', 'Community Outreach'],
    volunteers_needed: 10,
    volunteers_assigned: 6,
    description: 'Deliver school kits and books to children in remote tribal schools.',
    status: 'open',
  },
]
